name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  # 先共用一個 build job，避免重複安裝/編譯
  build_job:
    runs-on: ubuntu-latest
    name: Build Vue App
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist

  # 部署到第一個 SWA
  deploy_orange_plant:
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy to Azure Static Web Apps (Orange Plant)
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_PLANT_03636B100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          output_location: ""
          skip_app_build: true

  # 部署到第二個 SWA
  deploy_thankful_glacier:
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy to Azure Static Web Apps (Thankful Glacier)
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_GLACIER_06E1C3B00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          output_location: ""
          skip_app_build: true
